
spring:
  datasource:
    url: jdbc:mysql://192.168.8.11:13306/swarm_manager?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: hdtdmysqlserver2021


mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
server:
  port: 8081
  servlet:
    context-path: /